spring:
  application:
    name: spring-ai-deepseek-dome
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY:}  # 从环境变量或JVM参数获取
      chat:
        options:
          model: deepseek-chat
          temperature: 0.1 # 模型生成文本的随机程度。值越大，回复内容越赋有多样性、创造性、随机性;设为0根据事实回答。日常聊天建议设置为 0.7
    mcp:
      client:
        stdio:
          # Spring 会自动在 src/main/resources 目录查找文件
          servers-configuration: classpath:/mcp-server.json
        enabled: true
        type: sync
  datasource:
    url: jdbc:mysql://cd-cdb-dg1tsqr2.sql.tencentcdb.com:27806/db_study?charset=utf8mb4&parseTime=True&loc=Local
    username: dev_rd
    password: dev_rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # 明确指定方言
    hibernate:
      ddl-auto: update  # 自动更新表结构
    show-sql: true      # 显示 SQL 日志
server:
  port: 8080
logging:
  level:
    # 修正后的日志配置（删除重复包名）
    org.springframework.ai.chat.client.advisor: DEBUG
    # 显示完整工具调用过程
    org.springframework.ai.chat.client: DEBUG
    org.springframework.ai.model: TRACE
    # 可选：添加全局AI日志监控
    org.springframework.ai: INFO
ai:
  user:
    input: "有哪些工具可用?"